"""Add security fields for lockout

Revision ID: 85a39d3c8345
Revises: cf5557e221bb
Create Date: 2026-02-14 22:31:10.437654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a39d3c8345'
down_revision: Union[str, Sequence[str], None] = 'cf5557e221bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('lockout_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lockout_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
